<h3>18. Write a Program to implement Ensemble learning (Model 1: DT, Model 2: SVM, Model 3: Logistic, Model 4: KNN) using T-shirt size dataset.</h3><br>
<strong>Ensemble Learning:</strong> <p>Ensemble methods are meta-algorithms that combine several machine learning techniques into one predictive model in order to decrease variance (bagging), bias (boosting), or improve predictions (stacking).</p>
<img src=Ensemble_learning.png height=300 width=300>
<h5>Model 1: Logistic<br>Model 2 : Decision Tree<br>Model 3: SVM <br> Model 4: KNN</h5>

In [1]:
#importing Reauired library 
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [2]:
dataset= pd.read_excel('T-shirt dataset.xls')

In [3]:
dataset.shape

(26, 3)

In [4]:
dataset.head()

HEIGHT(IN CMS)  WEIGHT(IN KGS) T SHIRT SIZE
0             158              58            M
1             158              59            M
2             158              63            M
3             160              59            M
4             160              60            M

In [5]:
#independent attribute (height and weight)
x = dataset.iloc[:,[0,1]].values 
#dependent attribute T-shirt size
y = dataset.iloc[:,2].values
y

array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'L', 'L', 'L', 'L', 'L', 'L',
       'L', 'L', 'L', 'L', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M'],
      dtype=object)

As we know that our T-shirt column is categorical data, we have to encode this attribute. LabelEncoder is used for encoding the data.

In [6]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder() # le is an object from label encoder

In [7]:
y_new = y

In [8]:
y_new=le.fit_transform(y_new)

In [9]:
print(y) # values in the form of M / L
print(y_new) # values in the form of 1 and 0

['M' 'M' 'M' 'M' 'M' 'M' 'M' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M']
[1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]


In [10]:
y= y_new # updating y_new values in our target variable

<h3>Splitting data into train and test </h3>

In [11]:
# Split into training and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=7)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
model1_logistic = LogisticRegression()
model2_decision = DecisionTreeClassifier(max_depth=5) 
model3_SVM = SVC()
model4_KNN = KNeighborsClassifier(n_neighbors=3, metric='euclidean')

In [13]:
model1_logistic.fit(x_train, y_train)

LogisticRegression()

In [14]:
model2_decision.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5)

In [15]:
model3_SVM.fit(x_train, y_train)

SVC()

In [16]:
model4_KNN.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [17]:
y_pred1 = model1_logistic.predict(x_test) #LR
y_pred2 = model2_decision.predict(x_test) #DT
y_pred3 = model3_SVM.predict(x_test) #SVM
y_pred4 = model4_KNN.predict(x_test) #KNN

In [18]:
print("Actual y_test data : ", y_test)
print("Prediction by LR : ", y_pred1)
print("Prediction by DT :", y_pred2)
print("Prediction by SVM : ", y_pred3)
print("Prediction by KNN :", y_pred4)

Actual y_test data :  [0 1 1 0 0 0 1]
Prediction by LR :  [0 1 1 0 0 0 1]
Prediction by DT : [0 1 1 0 0 1 1]
Prediction by SVM :  [1 1 1 1 1 1 1]
Prediction by KNN : [0 1 1 0 0 1 1]


<h3>Evaluation of Model </h3>

In [19]:
#confusiojn matrix for different models 
from sklearn.metrics import confusion_matrix
cm_LR = confusion_matrix(y_test, y_pred1)
cm_DT = confusion_matrix(y_test, y_pred2)
cm_SVM = confusion_matrix(y_test, y_pred3)
cm_KNN = confusion_matrix(y_test, y_pred4)

In [20]:
print("Confusion_Matrix for LR:\n", cm_LR)
print("\nConfusion_Matrix for DT:\n", cm_DT)
print("\nConfusion_Matrix for SVM:\n",cm_SVM)
print("\nConfusion_Matrix for KNN:\n",cm_KNN)

Confusion_Matrix for LR:
 [[4 0]
 [0 3]]

Confusion_Matrix for DT:
 [[3 1]
 [0 3]]

Confusion_Matrix for SVM:
 [[0 4]
 [0 3]]

Confusion_Matrix for KNN:
 [[3 1]
 [0 3]]


In [21]:
#when we need to calculate the accuracy of model under classification
#always use testing dataset to get the result.
from sklearn.metrics import accuracy_score
LR_acc = accuracy_score(y_pred1, y_test)
DT_acc = accuracy_score(y_pred2, y_test)
SVM_acc = accuracy_score(y_pred3, y_test)
KNN_acc = accuracy_score(y_pred4, y_test)

In [22]:
print("Accuracy of LR:", LR_acc)
print("\nAccuracy of DT:", DT_acc)
print("\nAccuracy of SVM:",SVM_acc)
print("\nAccuracy of KNN:",KNN_acc)

Accuracy of LR: 1.0

Accuracy of DT: 0.8571428571428571

Accuracy of SVM: 0.42857142857142855

Accuracy of KNN: 0.8571428571428571


<h3>Ensemble Learning Model</h3>

<p>In this work, we have defined each of the four machine learning model 5 times (5*4=20). Then finally max voting classifier method is used where the class which has been predicted mostly by the week learners will be the fianl class prediction of the ensemble model. </p>

In [23]:
#estimator is a variable and it contains or append all the model details in list
estimator = []
#Definig 5 logistic Regression models
#model11, model12, model13, model14, model15 are the object of LR
model11=LogisticRegression()
estimator.append(('logistic1', model11))
model12=LogisticRegression()
estimator.append(('logistic2', model12))
model13=LogisticRegression()
estimator.append(('logistic3', model13))
model14=LogisticRegression()
estimator.append(('logistic4', model14))
model15=LogisticRegression()
estimator.append(('logistic5', model15))

#printing the value of estimators
estimator

[('logistic1', LogisticRegression()),
 ('logistic2', LogisticRegression()),
 ('logistic3', LogisticRegression()),
 ('logistic4', LogisticRegression()),
 ('logistic5', LogisticRegression())]

In [24]:
#Definig 5 Decision Tree models
#model21, model22, model23, model24, model25 are the object of DT
model21=DecisionTreeClassifier(max_depth = 2)
estimator.append(('cart1', model21))
model22=DecisionTreeClassifier(max_depth = 5)
estimator.append(('cart2', model22))
model23=DecisionTreeClassifier(max_depth = 3)
estimator.append(('cart3', model23))
model24=DecisionTreeClassifier(max_depth = 6)
estimator.append(('cart4', model24))
model25=DecisionTreeClassifier(max_depth = 1)
estimator.append(('cart5', model25))

#printing the value of estimators
estimator

[('logistic1', LogisticRegression()),
 ('logistic2', LogisticRegression()),
 ('logistic3', LogisticRegression()),
 ('logistic4', LogisticRegression()),
 ('logistic5', LogisticRegression()),
 ('cart1', DecisionTreeClassifier(max_depth=2)),
 ('cart2', DecisionTreeClassifier(max_depth=5)),
 ('cart3', DecisionTreeClassifier(max_depth=3)),
 ('cart4', DecisionTreeClassifier(max_depth=6)),
 ('cart5', DecisionTreeClassifier(max_depth=1))]

In [25]:
#Definig 5 SVM models
#model31, model32, model33, model34, model35 are the object of SVM
model31=SVC(kernel ='linear')
estimator.append(('svm1', model31))
model32=SVC(kernel ='rbf')
estimator.append(('svm2', model32))
model33=SVC(kernel ='linear')
estimator.append(('svm3', model33))
model34=SVC(kernel ='poly')
estimator.append(('svm4', model34))
model35=SVC(kernel ='linear')
estimator.append(('svm5', model35))

#printing the value of estimators
estimator

[('logistic1', LogisticRegression()),
 ('logistic2', LogisticRegression()),
 ('logistic3', LogisticRegression()),
 ('logistic4', LogisticRegression()),
 ('logistic5', LogisticRegression()),
 ('cart1', DecisionTreeClassifier(max_depth=2)),
 ('cart2', DecisionTreeClassifier(max_depth=5)),
 ('cart3', DecisionTreeClassifier(max_depth=3)),
 ('cart4', DecisionTreeClassifier(max_depth=6)),
 ('cart5', DecisionTreeClassifier(max_depth=1)),
 ('svm1', SVC(kernel='linear')),
 ('svm2', SVC()),
 ('svm3', SVC(kernel='linear')),
 ('svm4', SVC(kernel='poly')),
 ('svm5', SVC(kernel='linear'))]

In [26]:
#Definig 5 KNN models
#model41, model42, model43, model44, model45 are the object of KNN
model41=KNeighborsClassifier(n_neighbors = 3, metric ='euclidean')
estimator.append(('knn1', model41))
model42=KNeighborsClassifier(n_neighbors = 5, metric ='euclidean')
estimator.append(('knn2', model42))
model43=KNeighborsClassifier(n_neighbors = 4, metric ='euclidean')
estimator.append(('knn3', model43))
model44=KNeighborsClassifier(n_neighbors = 7, metric ='euclidean')
estimator.append(('knn4', model44))
model45=KNeighborsClassifier(n_neighbors = 2, metric ='euclidean')
estimator.append(('knn5', model45))

#printing the value of estimators
estimator

[('logistic1', LogisticRegression()),
 ('logistic2', LogisticRegression()),
 ('logistic3', LogisticRegression()),
 ('logistic4', LogisticRegression()),
 ('logistic5', LogisticRegression()),
 ('cart1', DecisionTreeClassifier(max_depth=2)),
 ('cart2', DecisionTreeClassifier(max_depth=5)),
 ('cart3', DecisionTreeClassifier(max_depth=3)),
 ('cart4', DecisionTreeClassifier(max_depth=6)),
 ('cart5', DecisionTreeClassifier(max_depth=1)),
 ('svm1', SVC(kernel='linear')),
 ('svm2', SVC()),
 ('svm3', SVC(kernel='linear')),
 ('svm4', SVC(kernel='poly')),
 ('svm5', SVC(kernel='linear')),
 ('knn1', KNeighborsClassifier(metric='euclidean', n_neighbors=3)),
 ('knn2', KNeighborsClassifier(metric='euclidean')),
 ('knn3', KNeighborsClassifier(metric='euclidean', n_neighbors=4)),
 ('knn4', KNeighborsClassifier(metric='euclidean', n_neighbors=7)),
 ('knn5', KNeighborsClassifier(metric='euclidean', n_neighbors=2))]

In [27]:
#At last we need to ensemble our models by using estimators 
#variable and fit the model using estimator varaible
#Defining the ensemble model
# here we are using VotingClassifier because it is basic 
#ensemble learning model, others are bagging and boosting classifier
from sklearn.ensemble import VotingClassifier
ensemble = VotingClassifier(estimator)
ensemble.fit(x_train, y_train)

VotingClassifier(estimators=[('logistic1', LogisticRegression()),
                             ('logistic2', LogisticRegression()),
                             ('logistic3', LogisticRegression()),
                             ('logistic4', LogisticRegression()),
                             ('logistic5', LogisticRegression()),
                             ('cart1', DecisionTreeClassifier(max_depth=2)),
                             ('cart2', DecisionTreeClassifier(max_depth=5)),
                             ('cart3', DecisionTreeClassifier(max_depth=3)),
                             ('cart4'...
                             ('svm4', SVC(kernel='poly')),
                             ('svm5', SVC(kernel='linear')),
                             ('knn1',
                              KNeighborsClassifier(metric='euclidean',
                                                   n_neighbors=3)),
                             ('knn2', KNeighborsClassifier(metric='euclidean')),
                    

In [28]:
y_pred = ensemble.predict(x_test)

In [29]:
y_pred

array([0, 1, 1, 0, 0, 1, 1])

In [30]:
y_test

array([0, 1, 1, 0, 0, 0, 1])

In [31]:
#confusion matrix
cm_Ensembler = confusion_matrix(y_test, y_pred)
cm_Ensembler

array([[3, 1],
       [0, 3]], dtype=int64)

In [32]:
acc_Ensembler = accuracy_score(y_pred, y_test)
print("Accuracy: ",acc_Ensembler)

Accuracy:  0.8571428571428571
